/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthActionRouteImport } from './routes/auth.action'
import { Route as AuthedRegisteredRouteImport } from './routes/_authed/_registered'
import { Route as AuthedAdminRouteImport } from './routes/_authed/_admin'
import { Route as AuthedRegisteredResultsRouteImport } from './routes/_authed/_registered/results'
import { Route as AuthedRegisteredQuizRouteImport } from './routes/_authed/_registered/quiz'
import { Route as AuthedRegisteredProfileRouteImport } from './routes/_authed/_registered/profile'
import { Route as AuthedRegisteredDashboardRouteImport } from './routes/_authed/_registered/dashboard'
import { Route as AuthedRegisteredCompanyRouteImport } from './routes/_authed/_registered/_company'
import { Route as AuthedAdminAdminRouteImport } from './routes/_authed/_admin/admin'
import { Route as AuthedRegisteredCompanyCompanySettingsRouteImport } from './routes/_authed/_registered/_company/company-settings'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthActionRoute = AuthActionRouteImport.update({
  id: '/auth/action',
  path: '/auth/action',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRegisteredRoute = AuthedRegisteredRouteImport.update({
  id: '/_registered',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRegisteredResultsRoute = AuthedRegisteredResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AuthedRegisteredRoute,
} as any)
const AuthedRegisteredQuizRoute = AuthedRegisteredQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => AuthedRegisteredRoute,
} as any)
const AuthedRegisteredProfileRoute = AuthedRegisteredProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRegisteredRoute,
} as any)
const AuthedRegisteredDashboardRoute =
  AuthedRegisteredDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthedRegisteredRoute,
  } as any)
const AuthedRegisteredCompanyRoute = AuthedRegisteredCompanyRouteImport.update({
  id: '/_company',
  getParentRoute: () => AuthedRegisteredRoute,
} as any)
const AuthedAdminAdminRoute = AuthedAdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedRegisteredCompanyCompanySettingsRoute =
  AuthedRegisteredCompanyCompanySettingsRouteImport.update({
    id: '/company-settings',
    path: '/company-settings',
    getParentRoute: () => AuthedRegisteredCompanyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/register': typeof RegisterRoute
  '/auth/action': typeof AuthActionRoute
  '/admin': typeof AuthedAdminAdminRoute
  '/dashboard': typeof AuthedRegisteredDashboardRoute
  '/profile': typeof AuthedRegisteredProfileRoute
  '/quiz': typeof AuthedRegisteredQuizRoute
  '/results': typeof AuthedRegisteredResultsRoute
  '/company-settings': typeof AuthedRegisteredCompanyCompanySettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/register': typeof RegisterRoute
  '/auth/action': typeof AuthActionRoute
  '/admin': typeof AuthedAdminAdminRoute
  '/dashboard': typeof AuthedRegisteredDashboardRoute
  '/profile': typeof AuthedRegisteredProfileRoute
  '/quiz': typeof AuthedRegisteredQuizRoute
  '/results': typeof AuthedRegisteredResultsRoute
  '/company-settings': typeof AuthedRegisteredCompanyCompanySettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/register': typeof RegisterRoute
  '/_authed/_admin': typeof AuthedAdminRouteWithChildren
  '/_authed/_registered': typeof AuthedRegisteredRouteWithChildren
  '/auth/action': typeof AuthActionRoute
  '/_authed/_admin/admin': typeof AuthedAdminAdminRoute
  '/_authed/_registered/_company': typeof AuthedRegisteredCompanyRouteWithChildren
  '/_authed/_registered/dashboard': typeof AuthedRegisteredDashboardRoute
  '/_authed/_registered/profile': typeof AuthedRegisteredProfileRoute
  '/_authed/_registered/quiz': typeof AuthedRegisteredQuizRoute
  '/_authed/_registered/results': typeof AuthedRegisteredResultsRoute
  '/_authed/_registered/_company/company-settings': typeof AuthedRegisteredCompanyCompanySettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/register'
    | '/auth/action'
    | '/admin'
    | '/dashboard'
    | '/profile'
    | '/quiz'
    | '/results'
    | '/company-settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/register'
    | '/auth/action'
    | '/admin'
    | '/dashboard'
    | '/profile'
    | '/quiz'
    | '/results'
    | '/company-settings'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_authed'
    | '/register'
    | '/_authed/_admin'
    | '/_authed/_registered'
    | '/auth/action'
    | '/_authed/_admin/admin'
    | '/_authed/_registered/_company'
    | '/_authed/_registered/dashboard'
    | '/_authed/_registered/profile'
    | '/_authed/_registered/quiz'
    | '/_authed/_registered/results'
    | '/_authed/_registered/_company/company-settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  AuthActionRoute: typeof AuthActionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/action': {
      id: '/auth/action'
      path: '/auth/action'
      fullPath: '/auth/action'
      preLoaderRoute: typeof AuthActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_registered': {
      id: '/_authed/_registered'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRegisteredRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_admin': {
      id: '/_authed/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_registered/results': {
      id: '/_authed/_registered/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AuthedRegisteredResultsRouteImport
      parentRoute: typeof AuthedRegisteredRoute
    }
    '/_authed/_registered/quiz': {
      id: '/_authed/_registered/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof AuthedRegisteredQuizRouteImport
      parentRoute: typeof AuthedRegisteredRoute
    }
    '/_authed/_registered/profile': {
      id: '/_authed/_registered/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedRegisteredProfileRouteImport
      parentRoute: typeof AuthedRegisteredRoute
    }
    '/_authed/_registered/dashboard': {
      id: '/_authed/_registered/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedRegisteredDashboardRouteImport
      parentRoute: typeof AuthedRegisteredRoute
    }
    '/_authed/_registered/_company': {
      id: '/_authed/_registered/_company'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRegisteredCompanyRouteImport
      parentRoute: typeof AuthedRegisteredRoute
    }
    '/_authed/_admin/admin': {
      id: '/_authed/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminAdminRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/_registered/_company/company-settings': {
      id: '/_authed/_registered/_company/company-settings'
      path: '/company-settings'
      fullPath: '/company-settings'
      preLoaderRoute: typeof AuthedRegisteredCompanyCompanySettingsRouteImport
      parentRoute: typeof AuthedRegisteredCompanyRoute
    }
  }
}

interface AuthedAdminRouteChildren {
  AuthedAdminAdminRoute: typeof AuthedAdminAdminRoute
}

const AuthedAdminRouteChildren: AuthedAdminRouteChildren = {
  AuthedAdminAdminRoute: AuthedAdminAdminRoute,
}

const AuthedAdminRouteWithChildren = AuthedAdminRoute._addFileChildren(
  AuthedAdminRouteChildren,
)

interface AuthedRegisteredCompanyRouteChildren {
  AuthedRegisteredCompanyCompanySettingsRoute: typeof AuthedRegisteredCompanyCompanySettingsRoute
}

const AuthedRegisteredCompanyRouteChildren: AuthedRegisteredCompanyRouteChildren =
  {
    AuthedRegisteredCompanyCompanySettingsRoute:
      AuthedRegisteredCompanyCompanySettingsRoute,
  }

const AuthedRegisteredCompanyRouteWithChildren =
  AuthedRegisteredCompanyRoute._addFileChildren(
    AuthedRegisteredCompanyRouteChildren,
  )

interface AuthedRegisteredRouteChildren {
  AuthedRegisteredCompanyRoute: typeof AuthedRegisteredCompanyRouteWithChildren
  AuthedRegisteredDashboardRoute: typeof AuthedRegisteredDashboardRoute
  AuthedRegisteredProfileRoute: typeof AuthedRegisteredProfileRoute
  AuthedRegisteredQuizRoute: typeof AuthedRegisteredQuizRoute
  AuthedRegisteredResultsRoute: typeof AuthedRegisteredResultsRoute
}

const AuthedRegisteredRouteChildren: AuthedRegisteredRouteChildren = {
  AuthedRegisteredCompanyRoute: AuthedRegisteredCompanyRouteWithChildren,
  AuthedRegisteredDashboardRoute: AuthedRegisteredDashboardRoute,
  AuthedRegisteredProfileRoute: AuthedRegisteredProfileRoute,
  AuthedRegisteredQuizRoute: AuthedRegisteredQuizRoute,
  AuthedRegisteredResultsRoute: AuthedRegisteredResultsRoute,
}

const AuthedRegisteredRouteWithChildren =
  AuthedRegisteredRoute._addFileChildren(AuthedRegisteredRouteChildren)

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRouteWithChildren
  AuthedRegisteredRoute: typeof AuthedRegisteredRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRouteWithChildren,
  AuthedRegisteredRoute: AuthedRegisteredRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AuthedRoute: AuthedRouteWithChildren,
  RegisterRoute: RegisterRoute,
  AuthActionRoute: AuthActionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
