run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - errorlint
    - gofmt
    - goimports
    - gocognit
    - gocyclo
    - gosec
    - prealloc
    - revive

linters-settings:
  gocyclo:
    min-complexity: 15
  gocognit:
    min-complexity: 15
  goimports:
    local-prefixes: factory-sync-solutions
  revive:
    rules:
      - name: exported
        severity: warning

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - errcheck
        - goconst
        - gosec
    - path: main\.go
      linters:
        - gochecknoinits
